Added German translations.
netzstrategen/drupal-ssofact pull request #7
Opened 2018-08-01 10:14 UTC by juliquiron

The strings are coming from the integration branch

2018-08-01 10:48 UTC, sun requested changes

2018-08-01 10:48 UTC, sun commented on translations/ssofact.de.po
> +msgstr "Ãœber das Modul"
The file does not seem to be encoded in UTF-8/Unicode… How was it created?

2018-08-01 10:48 UTC, sun commented on translations/ssofact.de.po
> +msgstr "Umfang"
This is a weird translation, but these technical OpenID Connect terms are hard to translate…

Can we remove all the translations that are not necessary right now and only add translations for the relevant strings in the user login form?

2018-08-01 10:48 UTC, sun commented on translations/ssofact.de.po
> +msgstr "E-Mailadresse"
Translated by Drupal core already.

2018-08-01 10:48 UTC, sun commented on translations/ssofact.de.po
> +msgstr "Passwort"
Translated by Drupal core already.

2018-08-01 10:48 UTC, sun commented on translations/ssofact.de.po
> +msgstr "Eingeloggt bleiben"
Needs to be the same string as in https://stage-login.stimme.de/ — "Angemeldet bleiben"

2018-08-01 10:48 UTC, sun commented on translations/ssofact.de.po
> +msgstr "Einloggen"
Needs to be the same string as in https://stage-login.stimme.de/ — "Anmelden"

2018-08-01 10:48 UTC, sun commented on translations/ssofact.de.po
> +msgstr "Ihre E-Mailadresse."
Seemingly translated by Drupal core already now?

If it is kept, then it needs to be "E-Mail-Adresse" and without trailing period.

2018-08-01 10:48 UTC, sun commented on translations/ssofact.de.po
> +msgstr "Ich akzeptiere die GeschÃ¤ftsbedingungen"
This is a longer text (see https://app.asana.com/0/633061025239778/732469091269190) and I doubt it makes sense to reverse-translate it into English

2018-08-01 10:48 UTC, sun commented on translations/ssofact.de.po
> +msgstr "Anmelden"
"Registrieren"

2018-08-01 10:48 UTC, sun commented on translations/ssofact.de.po
> +msgstr "RFBE SchlÃ¼ssel"
All strings starting from here are internal/administrative and should be removed

2018-08-14 17:04 UTC, juliquiron commented
All fixes applied, ready for new review. 

Changed the base to integration because in master there was not all the strings. I will try to move forward the merging of the paywall branch.

2018-08-16 19:14 UTC, sun commented
The branch paywall-juli is not in a functional state (fatal error), so that isn't a good/suitable base for this PR.  Perhaps `paywall-states-barriers` would be better?

2018-08-16 19:39 UTC, sun approved these changes
Removed the translations for administrative strings.

2018-08-16 19:39 UTC, sun commented on src/Form/SsofactRegisterForm.php
> +        ':url_info' => 'https://www.stimme-medien.de/metanavigation/informationspflichten/',
Hardcoding these is pretty bad… but I do not see a quick solution for this right now, so we need to come back to this later.

2018-08-27 10:30 UTC, merged